- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

coverage:
  status:
    project:
      default:
        threshold: 5%
        target: auto
      odfe-cli:
        paths:
          - "odfe-cli/"
        flags:
          - odfe-cli
    patch: off
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches: null
flags: